services:
  mongodb:
    container_name: mongodb_es4d
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - es4d-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  authservice:
    container_name: authservice_es4d
    build:
      context: ./users/authservice
      dockerfile: Dockerfile
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "8002:8002"
    networks:
      - es4d-net
    environment:
      MONGODB_URI: mongodb://mongodb:27017/usersdb
      TOKEN_SECRET_KEY: mi_clave_secreta

  userservice:
    container_name: userservice_es4d
    build:
      context: ./users/userservice
      dockerfile: Dockerfile
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "8001:8001"
    networks:
      - es4d-net
    environment:
      MONGODB_URI: mongodb://mongodb:27017/usersdb

  gamey:
    container_name: gamey_es4d
    build:
      context: ./gamey
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - es4d-net
    environment:
      PORT: 4000

  game:
    container_name: game_es4d
    build:
      context: ./game
      dockerfile: Dockerfile
    depends_on:
      userservice:
        condition: service_started
      gamey:
        condition: service_started
      mongodb:
        condition: service_healthy
    ports:
      - "8003:8003"
    networks:
      - es4d-net
    environment:
      PORT: 8003
      MONGODB_URI: mongodb://mongodb:27017/gamedb
      GAMEY_BOT_URL: http://gamey:4000

  friends:
    container_name: friends_es4d
    build:
      context: ./friends
      dockerfile: Dockerfile
    depends_on:
      userservice:
        condition: service_started
      authservice:
        condition: service_started
      mongodb:
        condition: service_healthy
    ports:
      - "8004:8004"
    networks:
      - es4d-net
    environment:
      PORT: 8004
      MONGODB_URI: mongodb://mongodb:27017/friendsdb
      USER_SERVICE_URL: http://userservice:8001
      TOKEN_SECRET_KEY: mi_clave_secreta

  gateway:
    container_name: gateway_es4d
    build:
      context: ./gateway
      dockerfile: Dockerfile
    depends_on:
      authservice:
        condition: service_started
      userservice:
        condition: service_started
      game:
        condition: service_started
      friends:
        condition: service_started
    ports:
      - "8000:8000"
    networks:
      - es4d-net
    environment:
      AUTH_SERVICE_URL: http://authservice:8002
      USER_SERVICE_URL: http://userservice:8001
      GAME_SERVICE_URL: http://game:8003
      FRIEND_SERVICE_URL: http://friends:8004
      TOKEN_SECRET_KEY: mi_clave_secreta

  webapp:
    container_name: webapp_es4d
    build:
      context: ./webapp
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8000
    depends_on:
      gateway:
        condition: service_started
    ports:
      - "5173:80"
    networks:
      - es4d-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus_es4d
    depends_on:
      gateway:
        condition: service_started
    ports:
      - "9090:9090"
    volumes:
      - ./gateway/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - es4d-net

  grafana:
    image: grafana/grafana
    container_name: grafana_es4d
    depends_on:
      prometheus:
        condition: service_started
    ports:
      - "9091:9091"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./gateway/monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SERVER_HTTP_PORT: 9091
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    networks:
      - es4d-net

volumes:
  mongodb_data:
  prometheus_data:
  grafana_data:

networks:
  es4d-net:
    driver: bridge
