sonar.organization=arquisoft
sonar.host.url=https://sonarcloud.io
sonar.projectKey=Arquisoft_yovi_es4d
sonar.projectName=yovi_es4d

# =========================
# SOURCES (solo código real)
# =========================
sonar.sources=webapp/src,gateway,friends,game,users/authservice,users/userservice

# =========================
# TESTS (todo lo de tests separado)
# =========================
sonar.tests=webapp/src,gateway,friends,game,users/authservice,users/userservice

# mejor detección de tests
sonar.test.inclusions=**/*.test.js,**/*.test.ts,**/*.test.tsx,**/*.spec.js,**/*.spec.ts,**/*.spec.tsx

# =========================
# EXCLUSIONES IMPORTANTES
# =========================
sonar.exclusions=**/node_modules/**,**/coverage/**,webapp/test/e2e/**,gamey/**

# gamey fuera porque no es JS/TS
sonar.coverage.exclusions=webapp/test/e2e/**,gamey/**

# =========================
# COVERAGE REPORTS
# =========================
sonar.javascript.lcov.reportPaths=\
webapp/coverage/lcov.info,\
gateway/coverage/lcov.info,\
friends/coverage/lcov.info,\
game/coverage/lcov.info,\
users/authservice/coverage/lcov.info,\
users/userservice/coverage/lcov.info