sonar.organization=arquisoft
sonar.host.url=https://sonarcloud.io
sonar.projectKey=Arquisoft_yovi_es4d
sonar.projectName=yovi_es4d

sonar.sources=webapp/src,gateway,friends,game,users/authservice,users/userservice,gamey/src
sonar.tests=webapp/src/__tests__,gateway,friends,game,users/authservice,users/userservice
sonar.test.inclusions=webapp/src/__tests__/**/*.test.tsx,gateway/**/*.test.js,friends/**/*.test.js,game/**/*.test.js,users/authservice/**/*.test.js,users/userservice/**/*.test.js

sonar.exclusions=**/node_modules/**,**/coverage/**,webapp/test/e2e/**,**/*.test.js,**/*.test.ts,**/*.test.tsx
sonar.coverage.exclusions=webapp/test/e2e/**,**/*.test.js,**/*.test.ts,**/*.test.tsx

sonar.javascript.lcov.reportPaths=webapp/coverage/lcov.info,gateway/coverage/lcov.info,friends/coverage/lcov.info,game/coverage/lcov.info,users/authservice/coverage/lcov.info,users/userservice/coverage/lcov.info
