ifndef::imagesdir[:imagesdir: ../images]

[[section-architecture-constraints]]
== ** Restricciones de Arquitectura**


ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Any requirement that constraints software architects in their freedom of design and implementation decisions or decision about the development process. These constraints sometimes go beyond individual systems and are valid for whole organizations and companies.

.Motivation
Architects should know exactly where they are free in their design decisions and where they must adhere to constraints.
Constraints must always be dealt with; they may be negotiable, though.

.Form
Simple tables of constraints with explanations.
If needed you can subdivide them into
technical constraints, organizational and political constraints and
conventions (e.g. programming or versioning guidelines, documentation or naming conventions)


.Further Information

See https://docs.arc42.org/section-2/[Architecture Constraints] in the arc42 documentation.

****
endif::arc42help[]

Esta sección se describen las restricciones técnicas, funcionales y de alcance que condicionan el diseño del sistema.

=== **Restricciones técnicas **
[cols="1,3", options="header"]
|===
|Restricción |Explicación

|**Acceso web**
|La aplicación deberá estar desplegada y ser accesible a través de la Web.

|**División de subsistemas**
|El sistema estará dividido en una Aplicación Web (frontend + API) y un módulo de lógica del juego.

|**Implementación web**
|La aplicación web debe estar implementada en TypeScript.

|**Módulo lógico**
|El módulo de lógica del juego debe estar implementado en Rust.

|**Intercambio de información**
|El intercambio de información entre la aplicación web y el módulo en Rust debe realizarse usando mensajes JSON, siguiendo la notación YEN.

|===

=== **Restricciones organizacionales **

[cols="1,3", options="header"]
|===
|Restricción |Explicación
|**Equipo**
|El equipo de desarrollo está conformado por 4 personas.

|**Reuniones**
|Se organizará al menos una reunioón semanal durante las clases de laboratorio donde se discutirá el proyecto y posibles impedimentos. 

|**Actas**
|Tras cada reunión se escribirá un acta donde se describen las decisiones que han sido tomadas
