ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Vista de tiempo de ejecución


ifdef::arc42help[]
[role="arc42help"]
****
.Contenido
La vista de ejecución (Runtime View) describe el comportamiento concreto y las interacciones de los bloques de construcción del sistema en forma de escenarios de las siguientes áreas:

* Casos de uso o funcionalidades importantes: ¿cómo los ejecutan los bloques de construcción?

* Interacciones en interfaces externas críticas: ¿cómo cooperan los bloques con usuarios y sistemas vecinos?

* Operación y administración: lanzamiento, inicio, parada

* Escenarios de error y excepción

Observación: El criterio principal para la selección de los posibles escenarios (secuencias, flujos de trabajo) es su relevancia arquitectónica. No es importante describir una gran cantidad de escenarios. Es preferible documentar una selección representativa.

.Form
* Existen muchas notaciones para describir escenarios, por ejemplo:

* Lista numerada de pasos (en lenguaje natural)

* Diagramas de actividad o diagramas de flujo

* Diagramas de secuencia

* BPMN o EPCs (cadenas de procesos dirigidas por eventos)

* Máquinas de estados

* ...


.Further Information

Consulta https://docs.arc42.org/section-6/[Runtime View] en la documentación de arc42.

****
endif::arc42help[]

=== Escenario 1: Registro de usuario
[plantuml,"Diagrama de secuencia:Registro",png]
----
actor usuario
database UserDB
usuario -> user-service: Registro con nombre de usuario, correo y contraseña
user-service --> user-service: Comprobación de datos
user-service --> UserDB: Almacenamiento de datos de usuario
UserDB --> user-service: Confirmación de datos almacenados
user-service --> usuario: Confirmación de registro exitoso
----

=== Escenario 2: Inicio de sesión
[plantuml,"Diagrama de secuencia:Inicio de sesión",png]
----
actor usuario
database UserDB
usuario -> user-service: Inicio de sesión con nombre de usuario y contraseña
user-service --> user-service: Comprobación de datos
user-service --> UserDB: Comprobación de datos de usuario
UserDB --> user-service: Confirmación de la existencia de los datos almacenados
user-service --> usuario: Confirmación de inicio de sesión exitoso
----

=== Escenario 3: Juego con el bot
[plantuml,"Diagrama de secuencia:Juego bot",png]
----
actor usuario
usuario -> webapp: Inicio de juego
webapp --> game: Solicitud de inicio de juego
game --> gamey: Pedida de datos para iniciar el juego
gamey --> game: Devuelta de datos para iniciar el juego
game --> webapp: Devuelta del tablero
webapp --> usuario: Visión del tablero
usuario -> webapp: Movimiento del jugador
webapp --> game: Envío del movimiento del jugador
game --> gamey: Envío y validación del movimiento del jugador a Rust 
gamey --> game: Devuelve el movimiento del jugador validado
game --> webapp: Devuelta del movimiento del jugador
webapp --> usuario: Visión del movimiento del jugador
webapp --> game: Solicitud de movimiento del bot
game --> gamey: Pedida y validación de movimiento del bot a Rust
gamey --> game: Devuelta del movimiento del bot validado
game --> webapp: Devuelta del movimiento del bot
webapp --> usuario: Visión del movimiento del bot

----
